name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for reporting your first issue in this repo!  I appreciate you reporting it.  I look forward to reviewing it.'' first issue'
        pr-message: 'Thank you for your first pull requests!  I appreciate your contribution.  I will review it shortly.'' first pr'
